version: "3"
services:
  app-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myDB
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - app-db
# Go to http://localhost:8080/MyWebApp